TITLES = [
    "Розробник", "Розробника", "Розробником",
    "Менеджер", "Менеджера", "Менеджером",
    "Інженер", "Інженера", "Інженером",
    "Дизайнер", "Дизайнера", "Дизайнером",
    "Керівник", "Керівника", "Керівником",
    "Аналітик", "Аналітика", "Аналітиком",
    "Архітектор", "Архітектора", "Архітектором",
    "Програміст", "Програміста", "Програмістом",
    "Адміністратор", "Адміністратора", "Адміністратором",
    "Тестувальник", "Тестувальника", "Тестувальником",
    "Продакт-менеджер", "Продакт-менеджера", "Продакт-менеджером",
    "Системний аналітик", "Системного аналітика", "Системним аналітиком",
    "Data Engineer", "Machine Learning Engineer", "DevOps",
    "Фахівець", "Фахівця", "Фахівцем",
    "Консультант", "Консультанта", "Консультантом"
]

COMPANIES = [
    "EPAM",
    "SoftServe",
    "GlobalLogic",
    "Luxoft",
    "Ciklum",
    "NIX Solutions",
    "DataArt",
    "EVOPLAY",
    "Intellias",
    "ZONE3000",
    "Infopulse",
    "Ajax Systems",
    "ELEKS",
    "Genesis",
    "N-iX",
    "Sigma Software",
    "Playrix",
    "Capgemini Engineering",
    "EVO",
    "SQUAD",
    "Grid Dynamics Group",
    "Netcracker",
    "Ubisoft",
    "AUTODOC",
    "Playtika",
    "Miratech",
    "Lohika",
    "Ring Ukraine",
    "Astound Commerce",
    "Innovecs",
    "Plarium",
    "ISD",
    "Intecracy Group",
    "GeeksForLess Inc.",
    "Astound Commerce",
    "Snap Inc",
    "ABBYY",
    "Rozetka",
    "JatApp",
    "Delasport",
    "Andersen",
    "Svitla Systems",
    "Brightgrove",
    "Gameloft",
    "Terrasoft/Creatio",
    "Viseven",
    "Promodex",
    "Fintech Band",
    "Playtika",
    "Playtech",
    "Prom",
    "TechSolutions",
    "DataInsight",
    "FinTechGuard",
    "Data Innovations",
    "Financial Services" ,
    "UPC"
]

EDUCATION = [
            'бакалавр',
            'магістр',
            'доктор',
            'аспірантура'
        ]
INSTITUTION = [
            'школа',
            'ліцей',
            'колледж',
            'університет',
            'навчальний центр',
        ]